# Generated by Django 4.1.4 on 2023-04-17 17:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0002_ratings_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="products",
            name="mrp",
            field=models.DecimalField(decimal_places=2, default=1, max_digits=16),
        ),
        migrations.AlterField(
            model_name="products",
            name="sell_price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
    ]
