# Generated by Django 4.1.4 on 2023-04-11 03:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0004_discount_products_discount_percentage_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="discount",
            name="created_on",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="discount",
            name="updated_on",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
